# Generated by Django 4.2.16 on 2024-11-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_ingredients_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.CreateModel(
            name='IngredientsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodgram.ingredients')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
